language: php

sudo: false

php:
  - 7.0
  - 7.1

env:
  - DEPENDENCIES=""
  - DEPENDENCIES="--prefer-lowest --prefer-stable"
  - DEPENDENCIES="--classmap-authoritative"
  - DEPENDENCIES="--no-scripts"

before_script:
  - sh .travis.install.sh

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml

after_script:
  - sh .travis.coverage.sh
